version: "3.9"
networks:
  microservices_network: 
    external: true
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - microservices_network
