apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Andrei\go\bin\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: frontend
