name: kwex_frontend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

  sonarcloud-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Run SonarCloud analysis
        run: |
          npm run build
          npx sonar-scanner \
            -Dsonar.projectKey=AndreiPieleanu_kwex_frontend \
            -Dsonar.organization=andreipieleanu \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: sonarcloud-check
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker --version

      - name: Build Docker image
        run: docker build -t kwex-frontend:latest .

      - name: Tag Docker image
        run: docker tag kwex-frontend:latest trainingtexas/kwex-frontend:latest

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push trainingtexas/kwex-frontend:latest
